## port
server:
  port: 8181

config:
  name: christli
  desc: spring-common-operation

configs:
  config:
    name: christli00
    desc: spring-common-operation-00

array-configs:
  configs:
    - name: christli01
      desc: spring-common-operation-01
    - name: christli02
      desc: spring-common-operation-02

spring:
  web:
    resources:
      static-locations: classpath:/templates/
##mail
  mail:
    host: smtp.163.com
    username: libinbin_christ@163.com
    password: xxxxx
    default-encoding: UTF-8

mail:
  fromMail:
    addr: libinbin_christ@163.com